"""
This module provides typing support for client package.
"""

from typing import Protocol

from .common import Address, EventLoop


class TcpClient(Protocol):
    def address(self) -> Address: ...
    def open(self, host: str, port: int): ...
    def close(self): ...
    async def read(self, n: int, loop: EventLoop) -> bytes: ...
    async def write(self, data: bytes, loop: EventLoop): ...
