"""
This module provides typing support for server package.
"""

from socket import socket
from typing import Tuple, Protocol

from .common import Address, EventLoop


class TcpServer(Protocol):
    def address(self) -> Address: ...
    def start(self, host: str, port: int): ...
    def stop(self): ...
    async def accept(self, loop: EventLoop) -> Tuple[socket, Address]: ...
    async def read(self, sock: socket, n: int, loop: EventLoop) -> bytes: ...
    async def write(self, sock: socket, data: bytes, loop: EventLoop): ...
